name: React CI with SonarQube

on:
  push:
    branches:
      - main
  

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test -- --coverage --watchAll=false
      continue-on-error: true

    - name: Build React App
      run: npm run build
      env:
        CI: false

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
